### ISSUE TITLE
GO SDK  is not returning an error when the signed URL is inaccessible

### ISSUE THREAD

**Issue by surakshith-suvarna** [AssemblyAI/assemblyai-go-sdk#32] opened 2024-11-05 13:43 UTC
I am using the TranscribeFromURL API to transcribe recordings stored in an S3 bucket. During testing with expired signed URLs, the SDK did not return an error response. Specifically, when an expired signed URL was passed, the condition err != nil did not trigger, and the execution continued until transcript.Text == nil.

My code snippet
`transcript, err := t.AIClient.Transcripts.TranscribeFromURL(ctx, signedURL, transcriptOptions)
	if err != nil {
		t.App.Logger.Errorf("[AITranscribe] Error while transcribing %v", err)
		return assemblyai.Transcript{}, "", err
	}
	if transcript.ID == nil {
		t.App.Logger.Error("[AITranscribe] Unable to transcribe the recordings")
		return assemblyai.Transcript{}, "", fmt.Errorf("unable to transcribe the recordings. Transcript ID is nil")
	}
	if transcript.Text == nil {
		t.App.Logger.Info("[AITranscribe] Transcript text is empty")
		t.InsertTranscriptError(recording, "Transcript text is empty", *transcript.ID)
		return transcript, "", nil
	}`
Upon checking the status on the Assembly AI Async Transcription page, the result was listed under the error section with the message: “Download error, unable to download S3_signed_url_link. Please make sure the file exists and is accessible from the internet.”

Expected Behavior:
The SDK should return this as an error, allowing us to retry with a new signed URL.

**Comment by marcusolsson** [comment] 2024-11-06 14:25
Thank you for reporting! 🙏 Marking as bug for now.

**Comment by marcusolsson** [comment] 2024-11-14 09:59
Looking closer at this, it seems like you were able to successfully submit the URL for transcription and get the transcript object. The reason why the SDK isn't returning an error is because it's not an _API_ error—the transcript is returned with a 200 status code.

Any errors during the actual transcription will be reported in the `transcript.Error` field:

```go
transcript, err := client.Transcripts.TranscribeFromURL(ctx, "https://nonexisting.foo", nil)
if err != nil {
    log.Fatal(err)
}

if transcript.Error != nil {
    log.Fatal("Transcription failed with error:", aai.ToString(transcript.Error))
}
```

If the transcription failed, you may still want to see the transcript for more information on why it may have failed.

I admit I would probably have made the same assumption as you did. While it's not a bug, I think we could make this clearer.

**Closed** 2024-11-25 11:16 UTC

**Comment by surakshith-suvarna** [comment] 2024-11-27 11:21
I apologize for missing the transcript.Error. I had assumed that err would catch all errors. Thank you for bringing this to my attention. I will review transcript.Error as well.
